# Django Backend Structure Guide for BwanguSpares
# =====================================================
# STANDALONE EXPORT GUIDE
# This document is the authoritative reference for migrating the BwanguSpares
# Base44 application to a self-hosted Django + PostgreSQL backend on a Linux server.
#
# HOW TO USE THIS GUIDE:
# 1. Provision a Linux server (Ubuntu 22.04 LTS recommended)
# 2. Follow "Server Setup" section to install system dependencies
# 3. Clone your repo and follow "Project Setup"
# 4. Create all Django apps listed in "Required Apps"
# 5. Copy models from DJANGO_MODELS_VIEWS_SERIALIZERS file into each app
# 6. Run migrations, seed initial data, and configure Nginx + Gunicorn
# 7. Point your React frontend's API base URL to the new Django server
#
# CURRENT BASE44 ENTITIES → DJANGO APPS MAPPING:
#   User, BannedUser          → users/
#   Region, Town              → regions/
#   Shop, Technician, Branch  → shops/
#   Vehicle                   → vehicles/
#   Product, ProductVariation → products/
#   CartItem                  → cart/
#   Order                     → orders/
#   Return                    → returns/
#   ShippingRate              → shipping/
#   Payment (Stripe)          → payments/
#   BuyerWallet, WalletTransaction, ShopWallet → wallet/
#   LoyaltyPoints, LoyaltyTransaction → loyalty/
#   Conversation, Message     → messaging/
#   PartsRequest              → parts_requests/
#   TechnicianHireRequest, Appointment → appointments/
#   Review                    → reviews/
#   Notification              → notifications/
#   DiscountCode              → discounts/
#   Wishlist, WatchlistPart   → wishlists/
#   Payout                    → payouts/
#   Report, AuditLog, SupportTicket → audit/
#   Subscription              → subscriptions/
#   Customer, Campaign        → marketing/
# =====================================================

## Project Root Directory Structure

```
bwangu-backend/
├── manage.py
├── requirements.txt
├── .env                          # Environment variables (NOT in git)
├── .env.example                  # Template for environment variables
├── .gitignore
├── Dockerfile
├── docker-compose.yml
├── config/
│   ├── __init__.py
│   ├── settings/
│   │   ├── __init__.py
│   │   ├── base.py               # Shared settings
│   │   ├── development.py        # Dev overrides
│   │   └── production.py         # Production overrides
│   ├── urls.py
│   ├── wsgi.py
│   └── asgi.py
├── staticfiles/                  # Collected static files (generated by collectstatic)
├── media/                        # User-uploaded files
├── logs/                         # Application logs
└── [apps]/                       # One folder per Django app (see Required Apps)
```

## Django App Internal Structure

Each app follows this layout:

```
[app_name]/
├── migrations/
│   ├── __init__.py
│   └── 0001_initial.py
├── __init__.py
├── admin.py
├── apps.py
├── models.py
├── serializers.py
├── views.py
├── urls.py
├── permissions.py
├── filters.py
├── signals.py                    # Post-save hooks (notifications, stock alerts)
├── tasks.py                      # Celery background tasks
└── tests.py
```

## Required Apps — Create All of These

```bash
python manage.py startapp users
python manage.py startapp regions
python manage.py startapp shops
python manage.py startapp vehicles
python manage.py startapp products
python manage.py startapp cart
python manage.py startapp orders
python manage.py startapp returns
python manage.py startapp shipping
python manage.py startapp payments
python manage.py startapp wallet
python manage.py startapp loyalty
python manage.py startapp messaging
python manage.py startapp parts_requests
python manage.py startapp appointments
python manage.py startapp reviews
python manage.py startapp notifications
python manage.py startapp discounts
python manage.py startapp wishlists
python manage.py startapp payouts
python manage.py startapp audit
python manage.py startapp subscriptions
python manage.py startapp marketing
```

## Configuration — config/settings/base.py

```python
import os
from pathlib import Path
from decouple import config, Csv
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    'django_filters',
    'rest_framework_simplejwt',
    'django_celery_beat',
    # Local apps
    'users',
    'regions',
    'shops',
    'vehicles',
    'products',
    'cart',
    'orders',
    'returns',
    'shipping',
    'payments',
    'wallet',
    'loyalty',
    'messaging',
    'parts_requests',
    'appointments',
    'reviews',
    'notifications',
    'discounts',
    'wishlists',
    'payouts',
    'audit',
    'subscriptions',
    'marketing',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.AuditLogMiddleware',  # Log all write operations
]

AUTH_USER_MODEL = 'users.User'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

CORS_ALLOWED_ORIGINS = config('CORS_ORIGINS', cast=Csv())
CORS_ALLOW_CREDENTIALS = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Stripe
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')

# Celery
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@bwangu.com')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'WARNING',
    },
}
```

## Environment Variables (.env)

```
# Django Core
DEBUG=False
SECRET_KEY=your-super-secret-key-minimum-50-chars
ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com,api.yourdomain.com
CORS_ORIGINS=https://yourdomain.com,https://www.yourdomain.com

# Database (PostgreSQL)
DB_NAME=bwangu_prod
DB_USER=bwangu_user
DB_PASSWORD=strong_password_here
DB_HOST=localhost
DB_PORT=5432

# Stripe
STRIPE_SECRET_KEY=sk_live_your_key
STRIPE_PUBLISHABLE_KEY=pk_live_your_key
STRIPE_WEBHOOK_SECRET=whsec_your_secret

# Email (SMTP)
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_HOST_USER=your-email@gmail.com
EMAIL_HOST_PASSWORD=your-app-password
DEFAULT_FROM_EMAIL=BwanguSpares <noreply@bwangu.com>

# Redis / Celery
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0

# File Storage (optional: use S3 for production uploads)
USE_S3=False
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_STORAGE_BUCKET_NAME=bwangu-media
```

## Dependencies (requirements.txt)

```
Django==4.2.13
djangorestframework==3.15.1
django-cors-headers==4.3.1
django-filter==23.5
psycopg2-binary==2.9.9
python-decouple==3.8
Pillow==10.3.0
stripe==9.5.0
celery==5.3.6
redis==5.0.4
django-celery-beat==2.6.0
gunicorn==22.0.0
whitenoise==6.6.0
djangorestframework-simplejwt==5.3.1
django-storages==1.14.2    # For S3 media storage
boto3==1.34.0               # If using S3
sentry-sdk==1.44.1          # Error monitoring
```

---

## Server Setup (Ubuntu 22.04 LTS)

### 1. System Dependencies
```bash
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y python3.11 python3.11-venv python3-pip
sudo apt-get install -y postgresql postgresql-contrib libpq-dev
sudo apt-get install -y redis-server
sudo apt-get install -y nginx supervisor certbot python3-certbot-nginx
sudo apt-get install -y git build-essential
```

### 2. PostgreSQL Setup
```sql
sudo -u postgres psql

CREATE DATABASE bwangu_prod;
CREATE USER bwangu_user WITH PASSWORD 'strong_password';
ALTER ROLE bwangu_user SET client_encoding TO 'utf8';
ALTER ROLE bwangu_user SET default_transaction_isolation TO 'read committed';
GRANT ALL PRIVILEGES ON DATABASE bwangu_prod TO bwangu_user;
\q
```

### 3. Project Setup
```bash
cd /var/www
git clone https://github.com/your-org/bwangu-backend.git
cd bwangu-backend

python3.11 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

cp .env.example .env
# Edit .env with your real values: nano .env

python manage.py migrate --settings=config.settings.production
python manage.py collectstatic --noinput --settings=config.settings.production
python manage.py createsuperuser --settings=config.settings.production
```

### 4. Data Migration from Base44
```bash
# Export data from Base44 using their export tool or API, then import:
# Each entity maps to a Django management command or fixture

python manage.py loaddata fixtures/regions.json
python manage.py loaddata fixtures/towns.json
python manage.py loaddata fixtures/shops.json
python manage.py loaddata fixtures/products.json
# ... repeat for each entity

# OR write a custom import script:
python manage.py import_from_base44 --entity=shops --file=exports/shops.json
```

### 5. Gunicorn (Supervisor)
Create `/etc/supervisor/conf.d/bwangu.conf`:
```ini
[program:bwangu]
directory=/var/www/bwangu-backend
command=/var/www/bwangu-backend/venv/bin/gunicorn config.wsgi:application \
    --bind 127.0.0.1:8000 \
    --workers 4 \
    --worker-class gthread \
    --threads 2 \
    --timeout 120 \
    --access-logfile /var/log/bwangu/gunicorn-access.log \
    --error-logfile /var/log/bwangu/gunicorn-error.log
autostart=true
autorestart=true
user=www-data
environment=DJANGO_SETTINGS_MODULE="config.settings.production"
```

### 6. Celery Workers (Supervisor)
Create `/etc/supervisor/conf.d/bwangu-celery.conf`:
```ini
[program:bwangu-celery]
directory=/var/www/bwangu-backend
command=/var/www/bwangu-backend/venv/bin/celery -A config worker -l info --concurrency=4
autostart=true
autorestart=true
user=www-data
stderr_logfile=/var/log/bwangu/celery-error.log
stdout_logfile=/var/log/bwangu/celery.log
environment=DJANGO_SETTINGS_MODULE="config.settings.production"

[program:bwangu-celery-beat]
directory=/var/www/bwangu-backend
command=/var/www/bwangu-backend/venv/bin/celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
autostart=true
autorestart=true
user=www-data
stderr_logfile=/var/log/bwangu/celery-beat-error.log
stdout_logfile=/var/log/bwangu/celery-beat.log
environment=DJANGO_SETTINGS_MODULE="config.settings.production"
```

Reload supervisor:
```bash
sudo mkdir -p /var/log/bwangu
sudo chown www-data:www-data /var/log/bwangu
sudo supervisorctl reread && sudo supervisorctl update
sudo supervisorctl start all
```

### 7. Nginx Configuration
Create `/etc/nginx/sites-available/bwangu`:
```nginx
upstream bwangu_app {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name yourdomain.com www.yourdomain.com api.yourdomain.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name yourdomain.com www.yourdomain.com api.yourdomain.com;
    client_max_body_size 20M;

    ssl_certificate /etc/letsencrypt/live/yourdomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yourdomain.com/privkey.pem;

    location /static/ {
        alias /var/www/bwangu-backend/staticfiles/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /var/www/bwangu-backend/media/;
    }

    location / {
        proxy_pass http://bwangu_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 90;
    }
}
```
```bash
sudo ln -s /etc/nginx/sites-available/bwangu /etc/nginx/sites-enabled/
sudo nginx -t && sudo systemctl reload nginx
```

### 8. SSL (Let's Encrypt)
```bash
sudo certbot --nginx -d yourdomain.com -d www.yourdomain.com
sudo systemctl enable certbot.timer
```

---

## Root URL Configuration (config/urls.py)

```python
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    # JWT Auth
    path('api/auth/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # App APIs
    path('api/users/', include('users.urls')),
    path('api/regions/', include('regions.urls')),
    path('api/shops/', include('shops.urls')),
    path('api/vehicles/', include('vehicles.urls')),
    path('api/products/', include('products.urls')),
    path('api/cart/', include('cart.urls')),
    path('api/orders/', include('orders.urls')),
    path('api/returns/', include('returns.urls')),
    path('api/shipping/', include('shipping.urls')),
    path('api/payments/', include('payments.urls')),
    path('api/wallet/', include('wallet.urls')),
    path('api/loyalty/', include('loyalty.urls')),
    path('api/messaging/', include('messaging.urls')),
    path('api/parts-requests/', include('parts_requests.urls')),
    path('api/appointments/', include('appointments.urls')),
    path('api/reviews/', include('reviews.urls')),
    path('api/notifications/', include('notifications.urls')),
    path('api/discounts/', include('discounts.urls')),
    path('api/wishlists/', include('wishlists.urls')),
    path('api/payouts/', include('payouts.urls')),
    path('api/audit/', include('audit.urls')),
    path('api/subscriptions/', include('subscriptions.urls')),
    path('api/marketing/', include('marketing.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

---

## Scheduled Tasks (Celery Beat — replaces Base44 automations)

The following tasks replace Base44 scheduled automations. Register them in the Django admin
under "Periodic Tasks" after running migrations:

| Base44 Automation            | Django Celery Task                        | Schedule         |
|------------------------------|-------------------------------------------|-----------------|
| autoPayoutShops              | payouts.tasks.auto_payout_shops           | Daily 01:00 CAT |
| autoPayoutAfter7Days         | payouts.tasks.auto_payout_after_7_days    | Daily 02:00 CAT |
| checkLowStock                | products.tasks.check_low_stock            | Every 6 hours   |
| notifyLowStock               | products.tasks.notify_low_stock           | Every 6 hours   |
| notifyNewReview              | reviews.tasks.notify_new_review           | On entity save  |
| notifyNewShop                | shops.tasks.notify_new_shop               | On entity save  |
| notifyOrderUpdate            | orders.tasks.notify_order_update          | On entity save  |
| notifyPartsRequest           | parts_requests.tasks.notify_parts_request | On entity save  |
| sendEmailCampaign            | marketing.tasks.send_email_campaign       | Scheduled       |
| generateSalesReport          | audit.tasks.generate_sales_report         | Weekly Monday   |
| deduplicateData              | audit.tasks.deduplicate_data              | Weekly Sunday   |
| checkWatchlistAlerts         | wishlists.tasks.check_watchlist_alerts    | Every 4 hours   |

Entity-save notifications should use **Django signals** (`post_save`) rather than scheduled tasks.

---

## React Frontend — Switching API Base URL

In your React app (Base44 export), update the API client to point to Django:

```javascript
// src/api/apiClient.js
const API_BASE = process.env.REACT_APP_API_URL || 'https://api.yourdomain.com';

export async function apiRequest(method, path, data = null) {
  const token = localStorage.getItem('access_token');
  const res = await fetch(`${API_BASE}${path}`, {
    method,
    headers: {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    body: data ? JSON.stringify(data) : null,
  });
  if (!res.ok) throw new Error(await res.text());
  return res.json();
}
```

---

## Stripe Webhook Setup (Django)

```python
# payments/views.py
import stripe
from django.conf import settings
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META.get('HTTP_STRIPE_SIGNATURE')
    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError:
        return HttpResponse(status=400)

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        order_id = session['metadata'].get('order_id')
        # Mark order as paid...

    return HttpResponse(status=200)
```

Register webhook endpoint in Stripe dashboard:
`https://api.yourdomain.com/api/payments/webhook/`

---

## Deployment Checklist

### Before Go-Live
- [ ] Set `DEBUG=False` and configure `ALLOWED_HOSTS`
- [ ] Use a strong, unique `SECRET_KEY` (50+ characters)
- [ ] Configure PostgreSQL with a dedicated user
- [ ] Run `python manage.py migrate` for all apps
- [ ] Run `python manage.py collectstatic`
- [ ] Configure Nginx + Gunicorn via Supervisor
- [ ] Obtain SSL certificate via Let's Encrypt
- [ ] Set Stripe live keys and register webhook
- [ ] Configure Redis for Celery task queue
- [ ] Test all API endpoints with Postman/Insomnia

### Data Migration from Base44
- [ ] Export all entities from Base44 (Settings → Export Data or use API)
- [ ] Write import management commands for each entity
- [ ] Validate record counts after import
- [ ] Migrate file/image URLs (re-upload to your media server or S3)
- [ ] Recreate admin user accounts
- [ ] Test end-to-end order flow on staging

### Post-Deployment
- [ ] Set up automated PostgreSQL backups (`pg_dump` via cron)
- [ ] Configure Sentry for error monitoring
- [ ] Set up uptime monitoring (UptimeRobot, Pingdom)
- [ ] Enable rate limiting (already configured in DRF settings above)
- [ ] Test Stripe payment flow end-to-end
- [ ] Verify email delivery
- [ ] Check Celery beat periodic tasks are running
- [ ] Set up log rotation for `/var/log/bwangu/`

---

## Maintenance Commands

```bash
# Apply new migrations after code changes
source venv/bin/activate
python manage.py migrate --settings=config.settings.production

# Collect new static files
python manage.py collectstatic --noinput --settings=config.settings.production

# Restart services
sudo supervisorctl restart bwangu bwangu-celery bwangu-celery-beat

# Database backup
pg_dump -U bwangu_user -h localhost bwangu_prod > /backups/bwangu_$(date +%Y%m%d).sql

# View logs
tail -f /var/log/bwangu/gunicorn-error.log
tail -f /var/log/bwangu/celery-error.log

# Django shell for debugging
python manage.py shell --settings=config.settings.production
`